### ISSUE TITLE
Implement code highlight feature with prismjs

### ISSUE THREAD

**Issue by Ckbhatia** [Ckbhatia/Ck-gatsby-blog#1]
Please integrate the code snippet highlight feature with prismJs

**Comment by mihirgupta0900** [comment]
Hey! Can I take up this issue?
And, do you have any PrismJS theme in mind or should I add what I feel looks good?

**Comment by Ckbhatia** [comment]
Hi, you can take it. Choose any theme that suits best. We can change it later if there's any need.
