### ISSUE TITLE
Implement filter articles by topics

### ISSUE THREAD

**Issue by Ckbhatia** [Ckbhatia/Ck-gatsby-blog#11]
**Implement filter articles by topics**

UI code is already available in Header.js component.

You need to implement filter article by topics.

Please star the project when you want to work on this issue or other.

**Comment by marcotgs** [comment]
Hi @Ckbhatia, I'd like to work on this issue.

**Comment by Ckbhatia** [comment]
Hi, I am glad to see your interest to work on this issue. I am assigning to you.

**Comment by Ckbhatia** [comment]
Hi @marcotgs, You this credential for articles data.

Don't need to set up your own contentful CMS for development

```
 CONTENTFUL_SPACE_ID=0dxfiyfxoovv
 CONTENTFUL_ACCESS_TOKEN=aQ8VH0ajavUGJur3I6LGRTZvjYf25s9ILko6bgLU9z8
```

**Comment by marcotgs** [comment]
Hi @Ckbhatia, I was thinking to create a new URL to show the filtered posts by topic, like this `topic/react`.

What do you think?

**Comment by Ckbhatia** [comment]
Sure, Go for it 👍

**Comment by Ckbhatia** [comment]
@marcotgs What's progress?

**Comment by marcotgs** [comment]
Hi @Ckbhatia, finishing up some styles. I'll open the PR today or tomorrow.
