### ISSUE TITLE
Add pagination feature

### ISSUE THREAD

**Issue by Ckbhatia** [Ckbhatia/Ck-gatsby-blog#13]
### Add pagination feature

The page should show six articles on each read more click and initially.

Desired result: 
![image](https://user-images.githubusercontent.com/37036881/95007773-0b703800-0631-11eb-8d0e-6920d717f977.png)

Use these env variables for development.

```
CONTENTFUL_SPACE_ID=0dxfiyfxoovv
CONTENTFUL_ACCESS_TOKEN=aQ8VH0ajavUGJur3I6LGRTZvjYf25s9ILko6bgLU9z8
```

Please star the project if you are interested to work on this issue and also don't hesitate to ask for help if you need.

**Comment by Ckbhatia** [comment]
Please take a checkout from feature branch

**Comment by Ckbhatia** [comment]
Foks, pick this issue as this is one of the easiest to implement as code is already there, you need to make some changes.

**Comment by saideepesh000** [comment]
@Ckbhatia, can i take this

**Comment by Ckbhatia** [comment]
@Ckbhatia I am glad to see your interest to work on this issue. I will be happy to see your PR for this issue.

**Comment by saideepesh000** [comment]
> 
> 
> @saideepesh000 I am glad to see your interest to work on this issue. I will be happy to see your PR for this issue.
> 
> P.s: Your star would help us

Please assign me officially otherwise someone would work on this.

**Comment by saideepesh000** [comment]
@Ckbhatia, Small doubt, Should I add the "read more" button and the feature because I can see that there isn't any "read more" button on the site.

**Comment by Ckbhatia** [comment]
Yes, please add it as given in image.

**Comment by Ckbhatia** [comment]
@saideepesh000 Can you quickly complete & raise PR?

**Comment by Ckbhatia** [comment]
It's up for pick

**Comment by ritikakhandelwal-17** [comment]
hey, I would like to work on this issue please assign it to me.

**Comment by Ckbhatia** [comment]
@ritikakhandelwal-17 You can raise a PR

**Comment by ritikakhandelwal-17** [comment]
@Ckbhatia just want to clarify some doubts. 
1. The code for showing blog list is in  /src/components/main_page/Arcticles.jsx file . Right?
2. Can I use some dummy data to check whether the feature is working correctly as there is no data from api.

**Comment by Ckbhatia** [comment]
1. Yes
2. Sure

**Comment by Ckbhatia** [comment]
You can use these development env: 

```
CONTENTFUL_SPACE_ID=0dxfiyfxoovv
CONTENTFUL_ACCESS_TOKEN=aQ8VH0ajavUGJur3I6LGRTZ
```
