### ISSUE TITLE
Link issues for CODE OF CONDUCT in CONTRIBUTING.md

### ISSUE THREAD

**Issue by sarthakvdev** [Ckbhatia/Ck-gatsby-blog#18]
There are issues with the link of CODE OF CONDUCT in CONTRIBUTING.md
I am correcting it and making a PR of this issue.

**Comment by Ckbhatia** [comment]
Sorry, But, these minor updates are already in the list for next major updates. So, I can't accept your PR or encourage people to fix this issue.

You can report other valid issue or pick any issue and fix it. 

Thanks
