### ISSUE TITLE
Implement make a network request on build time

### ISSUE THREAD

**Issue by Ckbhatia** [Ckbhatia/Ck-gatsby-blog#20]
### Add make a network request on build time

This project should make a network request to given URL with given data only if there's a new article published by the author.

Endpoint:
`https://cknewsletter.herokuapp.com/api/v1/projects/slug`

Request type: `Post`
Request payload: `{ "slug": "vue", "apiKey": "15870449476249g9uo****" }`

`slug`: It should be the latest article's slug or id only and make a network request if latest this is latest one and never made any request before for the same ( Or it can be handled by new build publish ).

`apiKey`: here you need to give project's API key obtained from [ck newsletter](https://cknewsletter.tech/)

It will push the newsletter to your subscribers of the particular project/blog.

Please read from here for more info: [ck newsletter guide](https://cknewsletter.tech/docs)

**Comment by sero-dev** [comment]
Can I get this issue?

**Comment by Ckbhatia** [comment]
@sero-dev I am glad to see your interest to work on this issue. I will be happy to see your PR for this issue.

P.s: Your star would help us

**Comment by Ckbhatia** [comment]
@sero-dev Hi, What's progress?

**Comment by sero-dev** [comment]
@Ckbhatia Hey, sorry I've been a bit busy. I might not have time to work on this.

**Comment by Ckbhatia** [comment]
Okay, No issues.

**Comment by Ckbhatia** [comment]
On HOLD
