### ISSUE TITLE
Improve project SEO

### ISSUE THREAD

**Issue by Ckbhatia** [Ckbhatia/Ck-gatsby-blog#21]
### Improve project SEO

Please take steps that improve the SEO of this project

Please star project when you want to contribute to this issue.

**Comment by anatdagan** [comment]
Please assign this issue to me.

**Comment by Ckbhatia** [comment]
@anatdagan I would love to see your PR for this issue.

Can let me know what steps are going to take?

**Comment by anatdagan** [comment]
Hi,
I'm planning to follow the suggestions in this tutorial: https://www.gatsbyjs.com/tutorial/seo-and-social-sharing-cards-tutorial/
Add an SEO component with social SEO and link rel=canonical

**Comment by Ckbhatia** [comment]
Go ahead 👍
