### ISSUE TITLE
Implement PWA

### ISSUE THREAD

**Issue by Ckbhatia** [Ckbhatia/Ck-gatsby-blog#24]
### Implement PWA

This app doesn't offer offline support or facilitate slow-internet connectivity.

PWA can be implemented with help of available gatsby plugins.

Take a checkout from `feature` branch and make PR against that.

P.S.: Please star the project when you want to contribute to this issue. It will help us.

**Comment by bhavika24** [comment]
Hi @Ckbhatia I would like to work on this. Please assign this to me.

**Comment by Ckbhatia** [comment]
I would love to see your PR for this issue. Go ahead @bhavika24
