### ISSUE TITLE
Render articles thumbnails 

### ISSUE THREAD

**Issue by Ckbhatia** [Ckbhatia/Ck-gatsby-blog#4]
Render articles thumbnails:

See this image:
![desired result](https://user-images.githubusercontent.com/37036881/94930567-3f8a1280-04e4-11eb-99ab-86bf3a1ed44c.png)

Current: 
![current result](https://user-images.githubusercontent.com/37036881/94930768-87a93500-04e4-11eb-894e-e82a01b62b56.png)

Set-up code is already there. You need to figure out and fix the bug that is causing this issue.

Feel free to reach out to me if you need any help.

Note: Please create .env.production and paste same env variables there else it might not work for you.

P.S: Please star this repo if you have visited this.

**Comment by sagarchoudhary96** [comment]
@Ckbhatia can i look into this issue ?

**Comment by sagarchoudhary96** [comment]
Also can you let me know the steps to run this locally to see this above page, i tried `npm install` then `npm start` but it throws error :
<img width="422" alt="Screenshot 2020-10-02 at 7 43 57 PM" src="https://user-images.githubusercontent.com/16102594/94933150-a0ffb080-04e7-11eb-8fd6-c95762fdc0c8.png">

**Comment by Ckbhatia** [comment]
You need contentful API tokens. Check set-up guide in readme.

**Comment by sagarchoudhary96** [comment]
yes but it says in readme that: 'It's optional to set-up contentful CMS.'

**Comment by Ckbhatia** [comment]
Sorry, you need to setup else you need to change configuration.

Or wait, I will make changes.

**Comment by sagarchoudhary96** [comment]
@Ckbhatia  let me know once done

**Comment by sagarchoudhary96** [comment]
Also can you assign it to me

**Comment by Ckbhatia** [comment]
@sagarchoudhary96 I am glad to see your interest to work on this issue. I have this issue for now.

Can you look for another issue, I will assign you that?
