### ISSUE TITLE
Add landing page preview to README

### ISSUE THREAD

**Issue by Ckbhatia** [Ckbhatia/Ck-gatsby-blog#7]
Add landing page preview to README:

First page:
![landingPage](https://user-images.githubusercontent.com/37036881/94952450-a3700380-0503-11eb-8012-af1ac66ec301.png)

Second page:
![articles](https://user-images.githubusercontent.com/37036881/94952500-b682d380-0503-11eb-83fb-c07fe1476ad0.png)

Note: the second page is optional. Only add if fits well.

Please don't forget to star the project if you want to contribute.

**Comment by NishithP2004** [comment]
Hi, could you please assign me to this issue?

**Comment by harshita130602** [comment]
Hey! I would love to contribute to this issue. Could you please assign it to me

**Comment by Ckbhatia** [comment]
I am making some changes to the requirements. Let me see if I can assign anyone of you after that.

**Comment by Utpal29** [comment]
hi, can you assign me this task?

**Comment by Ckbhatia** [comment]
@Utpal29 I am glad to see your interest to work on this issue. I have some changes to make. So, I will work on this issue.

You can look for other issues and show interest, I will assign one.
